# Generated by Django 5.0.14 on 2025-06-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_satff'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE user (
            ID INT PRIMARY KEY IDENTITY(1,1),
            Password NVARCHAR(50) NOT NULL,
            UserName NVARCHAR(50) NOT NULL UNIQUE,
            is_staff INT NOT NULL CHECK (is_staff IN (0,1))
);
    CREATE TABLE Dr (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
    Gender NVARCHAR(2) NOT NULL CHECK (Gender IN ('男', '女')),
    Position NVARCHAR(50) NOT NULL,
    BirthDate DATE NOT NULL,
    Whentowork DATE NOT NULL,
    JoinDate DATE NOT NULL,
    Salary DECIMAL(10,2) NOT NULL CHECK (Salary >= 0),
    About NVARCHAR(500) DEFAULT '无',
    BID NVARCHAR(20) FOREIGN KEY REFERENCES bumen(DeptID)
);
     CREATE TABLE bumen (
    BID NVARCHAR(20) PRIMARY KEY,               -- 部门编号，主键
    Name NVARCHAR(50) NOT NULL UNIQUE          -- 部门名称，非空且唯一
);

-- 创建科室表：存储医疗科室信息（如内科、外科）
    CREATE TABLE keshi (
    KID NVARCHAR(20) PRIMARY KEY,               -- 科室编号，主键
    Name NVARCHAR(50) NOT NULL UNIQUE          -- 科室名称，非空且唯一
);

            """
        ),
    ]
